apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-copycat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "k8s-copycat.labels" . | indent 4 }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.commonAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "k8s-copycat.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "k8s-copycat.selectorLabels" . | indent 8 }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- $podAnnotations := merge (dict) (default (dict) .Values.commonAnnotations) (default (dict) .Values.podAnnotations) }}
{{- if $podAnnotations }}
      annotations:
{{ toYaml $podAnnotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "k8s-copycat.serviceAccountName" . }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
{{- end }}
{{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: k8s-copycat
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.command }}
          command:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.args }}
          args:
{{ toYaml . | indent 12 }}
{{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.containerPorts.metrics }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.containerPorts.health }}
              protocol: TCP
{{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
{{- end }}
{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
{{- $probe := omit .Values.livenessProbe "enabled" }}
{{ toYaml $probe | indent 12 }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
{{- $probe := omit .Values.readinessProbe "enabled" }}
{{ toYaml $probe | indent 12 }}
{{- end }}
{{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
{{- if or .Values.configMap.create .Values.configMap.existingConfigMap .Values.extraVolumeMounts }}
          volumeMounts:
{{- if or .Values.configMap.create .Values.configMap.existingConfigMap }}
            - name: config
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
{{- end }}
{{- with .Values.extraVolumeMounts }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end }}
{{- with .Values.extraEnv }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.extraEnvFrom }}
          envFrom:
{{ toYaml . | indent 12 }}
{{- end }}
{{- if or .Values.configMap.create .Values.configMap.existingConfigMap .Values.extraVolumes }}
      volumes:
{{- if or .Values.configMap.create .Values.configMap.existingConfigMap }}
        - name: config
          configMap:
            name: {{ include "k8s-copycat.configMapName" . }}
            {{- with .Values.configMap.defaultMode }}
            defaultMode: {{ . }}
            {{- end }}
            items:
              - key: {{ .Values.configMap.key }}
                path: {{ .Values.configMap.filename }}
{{- end }}
{{- with .Values.extraVolumes }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podTopologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
{{- end }}
